// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRshZCr5Pp68USshJihAzZ_PA-M1Yhdaw',
    appId: '1:989766721878:web:6d5cce1786e797980676f7',
    messagingSenderId: '989766721878',
    projectId: 'bloom-period-tracker-89849',
    authDomain: 'bloom-period-tracker-89849.firebaseapp.com',
    storageBucket: 'bloom-period-tracker-89849.firebasestorage.app',
    measurementId: 'G-4JX5F0E65K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsHZeJkrRUFZg0-ocWJDiphgbPw9Xjc4k',
    appId: '1:989766721878:android:b679152155c114f70676f7',
    messagingSenderId: '989766721878',
    projectId: 'bloom-period-tracker-89849',
    storageBucket: 'bloom-period-tracker-89849.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-r-Yoxfy-HeV1146hQsak6S-sMttsOBs',
    appId: '1:989766721878:ios:68049639a53ffd8c0676f7',
    messagingSenderId: '989766721878',
    projectId: 'bloom-period-tracker-89849',
    storageBucket: 'bloom-period-tracker-89849.firebasestorage.app',
    iosBundleId: 'com.example.bloomCycle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRshZCr5Pp68USshJihAzZ_PA-M1Yhdaw',
    appId: '1:989766721878:web:6af6d2e390633a380676f7',
    messagingSenderId: '989766721878',
    projectId: 'bloom-period-tracker-89849',
    authDomain: 'bloom-period-tracker-89849.firebaseapp.com',
    storageBucket: 'bloom-period-tracker-89849.firebasestorage.app',
    measurementId: 'G-40L7EKFF07',
  );
}
